INFO 2019-01-15 22:28:03,956 basehttp 124 "GET / HTTP/1.1" 200 16286
INFO 2019-01-15 22:28:03,991 basehttp 124 "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
INFO 2019-01-15 22:28:04,028 basehttp 124 "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 82564
INFO 2019-01-15 22:28:04,074 basehttp 124 "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 81348
INFO 2019-01-15 22:28:04,080 basehttp 124 "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 80304
WARNING 2019-01-15 22:28:04,124 log 228 Not Found: /favicon.ico
WARNING 2019-01-15 22:28:04,126 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 1982
INFO 2019-01-15 22:54:08,071 basehttp 124 "GET / HTTP/1.1" 200 16934
WARNING 2019-01-15 22:54:08,130 log 228 Not Found: /css/base/common.css
WARNING 2019-01-15 22:54:08,137 basehttp 124 "GET /css/base/common.css HTTP/1.1" 404 2586
WARNING 2019-01-15 22:54:08,134 log 228 Not Found: /css/base/reset.css
WARNING 2019-01-15 22:54:08,141 log 228 Not Found: /css/news/index.css
WARNING 2019-01-15 22:54:08,141 basehttp 124 "GET /css/base/reset.css HTTP/1.1" 404 2583
WARNING 2019-01-15 22:54:08,145 basehttp 124 "GET /css/news/index.css HTTP/1.1" 404 2583
WARNING 2019-01-15 22:54:08,152 log 228 Not Found: /css/base/side.css
WARNING 2019-01-15 22:54:08,164 basehttp 124 "GET /css/base/side.css HTTP/1.1" 404 2580
WARNING 2019-01-15 22:54:08,159 log 228 Not Found: /images/python_gui.jpg
WARNING 2019-01-15 22:54:08,162 log 228 Not Found: /images/linux.jpg
WARNING 2019-01-15 22:54:08,178 basehttp 124 "GET /images/linux.jpg HTTP/1.1" 404 2577
WARNING 2019-01-15 22:54:08,179 basehttp 124 "GET /images/python_gui.jpg HTTP/1.1" 404 2592
WARNING 2019-01-15 22:54:08,173 log 228 Not Found: /js/base/common.js
WARNING 2019-01-15 22:54:08,184 basehttp 124 "GET /js/base/common.js HTTP/1.1" 404 2580
WARNING 2019-01-15 22:54:08,183 log 228 Not Found: /js/index.js
WARNING 2019-01-15 22:54:08,191 basehttp 124 "GET /js/index.js HTTP/1.1" 404 2562
WARNING 2019-01-15 22:54:08,189 log 228 Not Found: /images/python_function.jpg
WARNING 2019-01-15 22:54:08,193 basehttp 124 "GET /images/python_function.jpg HTTP/1.1" 404 2607
WARNING 2019-01-15 22:54:08,204 log 228 Not Found: /images/python_advanced.jpg
WARNING 2019-01-15 22:54:08,211 basehttp 124 "GET /images/python_advanced.jpg HTTP/1.1" 404 2607
WARNING 2019-01-15 22:54:08,209 log 228 Not Found: /images/jichujiaochen.jpeg
WARNING 2019-01-15 22:54:08,214 basehttp 124 "GET /images/jichujiaochen.jpeg HTTP/1.1" 404 2604
WARNING 2019-01-15 22:54:08,220 log 228 Not Found: /images/python_web.jpg
WARNING 2019-01-15 22:54:08,227 basehttp 124 "GET /images/python_web.jpg HTTP/1.1" 404 2592
WARNING 2019-01-15 22:54:08,226 log 228 Not Found: /images/english.jpg
WARNING 2019-01-15 22:54:08,229 basehttp 124 "GET /images/english.jpg HTTP/1.1" 404 2583
WARNING 2019-01-15 22:54:08,976 log 228 Not Found: /js/base/common.js
WARNING 2019-01-15 22:54:08,977 basehttp 124 "GET /js/base/common.js HTTP/1.1" 404 2580
WARNING 2019-01-15 22:54:08,990 log 228 Not Found: /js/index.js
WARNING 2019-01-15 22:54:08,992 basehttp 124 "GET /js/index.js HTTP/1.1" 404 2562
INFO 2019-01-16 08:22:27,588 basehttp 124 "GET / HTTP/1.1" 200 16934
WARNING 2019-01-16 08:22:27,691 log 228 Not Found: /css/base/reset.css
WARNING 2019-01-16 08:22:27,707 basehttp 124 "GET /css/base/reset.css HTTP/1.1" 404 2583
WARNING 2019-01-16 08:22:27,694 log 228 Not Found: /css/base/common.css
WARNING 2019-01-16 08:22:27,711 basehttp 124 "GET /css/base/common.css HTTP/1.1" 404 2586
WARNING 2019-01-16 08:22:27,698 log 228 Not Found: /css/news/index.css
WARNING 2019-01-16 08:22:27,713 basehttp 124 "GET /css/news/index.css HTTP/1.1" 404 2583
WARNING 2019-01-16 08:22:27,702 log 228 Not Found: /css/base/side.css
WARNING 2019-01-16 08:22:27,706 log 228 Not Found: /images/linux.jpg
WARNING 2019-01-16 08:22:27,727 basehttp 124 "GET /images/linux.jpg HTTP/1.1" 404 2577
WARNING 2019-01-16 08:22:27,728 basehttp 124 "GET /css/base/side.css HTTP/1.1" 404 2580
WARNING 2019-01-16 08:22:27,722 log 228 Not Found: /images/python_gui.jpg
WARNING 2019-01-16 08:22:27,735 basehttp 124 "GET /images/python_gui.jpg HTTP/1.1" 404 2592
WARNING 2019-01-16 08:22:27,738 log 228 Not Found: /js/base/common.js
WARNING 2019-01-16 08:22:27,749 basehttp 124 "GET /js/base/common.js HTTP/1.1" 404 2580
WARNING 2019-01-16 08:22:27,746 log 228 Not Found: /js/index.js
WARNING 2019-01-16 08:22:27,758 basehttp 124 "GET /js/index.js HTTP/1.1" 404 2562
WARNING 2019-01-16 08:22:27,756 log 228 Not Found: /images/python_function.jpg
WARNING 2019-01-16 08:22:27,765 basehttp 124 "GET /images/python_function.jpg HTTP/1.1" 404 2607
WARNING 2019-01-16 08:22:27,763 log 228 Not Found: /images/python_advanced.jpg
WARNING 2019-01-16 08:22:27,771 basehttp 124 "GET /images/python_advanced.jpg HTTP/1.1" 404 2607
WARNING 2019-01-16 08:22:27,781 log 228 Not Found: /images/jichujiaochen.jpeg
WARNING 2019-01-16 08:22:27,791 basehttp 124 "GET /images/jichujiaochen.jpeg HTTP/1.1" 404 2604
WARNING 2019-01-16 08:22:27,790 log 228 Not Found: /images/python_web.jpg
WARNING 2019-01-16 08:22:27,805 basehttp 124 "GET /images/python_web.jpg HTTP/1.1" 404 2592
WARNING 2019-01-16 08:22:27,810 log 228 Not Found: /images/english.jpg
WARNING 2019-01-16 08:22:27,812 basehttp 124 "GET /images/english.jpg HTTP/1.1" 404 2583
WARNING 2019-01-16 08:22:28,226 log 228 Not Found: /js/base/common.js
WARNING 2019-01-16 08:22:28,227 basehttp 124 "GET /js/base/common.js HTTP/1.1" 404 2580
WARNING 2019-01-16 08:22:28,236 log 228 Not Found: /js/index.js
WARNING 2019-01-16 08:22:28,238 basehttp 124 "GET /js/index.js HTTP/1.1" 404 2562
WARNING 2019-01-16 08:22:28,254 log 228 Not Found: /favicon.ico
WARNING 2019-01-16 08:22:28,255 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2562
INFO 2019-01-16 09:10:13,271 basehttp 124 "GET / HTTP/1.1" 200 17019
INFO 2019-01-16 09:10:13,330 basehttp 124 "GET /static/css/base/reset.css HTTP/1.1" 200 1427
INFO 2019-01-16 09:10:13,332 basehttp 124 "GET /static/css/base/common.css HTTP/1.1" 200 3498
INFO 2019-01-16 09:10:13,333 basehttp 124 "GET /static/css/news/index.css HTTP/1.1" 200 5500
INFO 2019-01-16 09:10:13,348 basehttp 124 "GET /static/css/base/side.css HTTP/1.1" 200 4428
WARNING 2019-01-16 09:10:13,361 log 228 Not Found: /images/linux.jpg
WARNING 2019-01-16 09:10:13,371 basehttp 124 "GET /images/linux.jpg HTTP/1.1" 404 2577
WARNING 2019-01-16 09:10:13,369 log 228 Not Found: /images/python_gui.jpg
WARNING 2019-01-16 09:10:13,377 basehttp 124 "GET /images/python_gui.jpg HTTP/1.1" 404 2592
WARNING 2019-01-16 09:10:13,375 log 228 Not Found: /images/python_function.jpg
WARNING 2019-01-16 09:10:13,386 basehttp 124 "GET /images/python_function.jpg HTTP/1.1" 404 2607
WARNING 2019-01-16 09:10:13,395 log 228 Not Found: /js/index.js
WARNING 2019-01-16 09:10:13,408 basehttp 124 "GET /js/index.js HTTP/1.1" 404 2562
WARNING 2019-01-16 09:10:13,404 log 228 Not Found: /js/base/common.js
WARNING 2019-01-16 09:10:13,410 basehttp 124 "GET /js/base/common.js HTTP/1.1" 404 2580
WARNING 2019-01-16 09:10:13,418 log 228 Not Found: /images/python_advanced.jpg
WARNING 2019-01-16 09:10:13,423 basehttp 124 "GET /images/python_advanced.jpg HTTP/1.1" 404 2607
WARNING 2019-01-16 09:10:13,428 log 228 Not Found: /images/english.jpg
WARNING 2019-01-16 09:10:13,439 basehttp 124 "GET /images/english.jpg HTTP/1.1" 404 2583
WARNING 2019-01-16 09:10:13,443 log 228 Not Found: /images/python_web.jpg
WARNING 2019-01-16 09:10:13,444 basehttp 124 "GET /images/python_web.jpg HTTP/1.1" 404 2592
WARNING 2019-01-16 09:10:13,447 log 228 Not Found: /images/jichujiaochen.jpeg
WARNING 2019-01-16 09:10:13,451 basehttp 124 "GET /images/jichujiaochen.jpeg HTTP/1.1" 404 2604
INFO 2019-01-16 09:10:13,457 basehttp 124 "GET /static/images/wechat.jpg HTTP/1.1" 200 24527
WARNING 2019-01-16 09:10:13,476 log 228 Not Found: /js/index.js
WARNING 2019-01-16 09:10:13,479 basehttp 124 "GET /js/index.js HTTP/1.1" 404 2562
WARNING 2019-01-16 09:10:17,400 log 228 Not Found: /course/course.html
WARNING 2019-01-16 09:10:17,402 basehttp 124 "GET /course/course.html HTTP/1.1" 404 2644
WARNING 2019-01-16 09:10:31,592 log 228 Not Found: /course/course.html
WARNING 2019-01-16 09:10:31,595 basehttp 124 "GET /course/course.html HTTP/1.1" 404 2644
INFO 2019-01-16 09:11:33,468 basehttp 124 "GET / HTTP/1.1" 200 17019
WARNING 2019-01-16 09:11:33,506 log 228 Not Found: /images/linux.jpg
WARNING 2019-01-16 09:11:33,514 basehttp 124 "GET /images/linux.jpg HTTP/1.1" 404 2577
WARNING 2019-01-16 09:11:33,511 log 228 Not Found: /images/python_gui.jpg
WARNING 2019-01-16 09:11:33,520 basehttp 124 "GET /images/python_gui.jpg HTTP/1.1" 404 2592
WARNING 2019-01-16 09:11:33,535 log 228 Not Found: /js/index.js
WARNING 2019-01-16 09:11:33,547 basehttp 124 "GET /js/index.js HTTP/1.1" 404 2562
WARNING 2019-01-16 09:11:33,542 log 228 Not Found: /js/base/common.js
WARNING 2019-01-16 09:11:33,555 basehttp 124 "GET /js/base/common.js HTTP/1.1" 404 2580
WARNING 2019-01-16 09:11:33,547 log 228 Not Found: /images/python_advanced.jpg
WARNING 2019-01-16 09:11:33,559 basehttp 124 "GET /images/python_advanced.jpg HTTP/1.1" 404 2607
WARNING 2019-01-16 09:11:33,563 log 228 Not Found: /images/python_function.jpg
WARNING 2019-01-16 09:11:33,569 basehttp 124 "GET /images/python_function.jpg HTTP/1.1" 404 2607
WARNING 2019-01-16 09:11:33,573 log 228 Not Found: /images/english.jpg
WARNING 2019-01-16 09:11:33,582 basehttp 124 "GET /images/english.jpg HTTP/1.1" 404 2583
WARNING 2019-01-16 09:11:33,581 log 228 Not Found: /images/jichujiaochen.jpeg
WARNING 2019-01-16 09:11:33,594 basehttp 124 "GET /images/jichujiaochen.jpeg HTTP/1.1" 404 2604
WARNING 2019-01-16 09:11:33,599 log 228 Not Found: /images/python_web.jpg
WARNING 2019-01-16 09:11:33,607 basehttp 124 "GET /images/python_web.jpg HTTP/1.1" 404 2592
WARNING 2019-01-16 09:11:33,606 log 228 Not Found: /js/index.js
WARNING 2019-01-16 09:11:33,609 basehttp 124 "GET /js/index.js HTTP/1.1" 404 2562
WARNING 2019-01-16 09:11:34,687 log 228 Not Found: /index.html
WARNING 2019-01-16 09:11:34,688 basehttp 124 "GET /index.html HTTP/1.1" 404 2559
WARNING 2019-01-16 09:11:38,179 log 228 Not Found: /images/python_function.jpg
WARNING 2019-01-16 09:11:38,180 basehttp 124 "GET /images/python_function.jpg HTTP/1.1" 404 2607
WARNING 2019-01-16 09:11:38,980 log 228 Not Found: /course/course.html
WARNING 2019-01-16 09:11:38,982 basehttp 124 "GET /course/course.html HTTP/1.1" 404 2652
INFO 2019-01-16 09:27:37,543 basehttp 124 "GET / HTTP/1.1" 200 17051
WARNING 2019-01-16 09:27:37,577 log 228 Not Found: /images/python_gui.jpg
WARNING 2019-01-16 09:27:37,598 basehttp 124 "GET /images/python_gui.jpg HTTP/1.1" 404 2592
WARNING 2019-01-16 09:27:37,600 log 228 Not Found: /images/linux.jpg
WARNING 2019-01-16 09:27:37,610 basehttp 124 "GET /images/linux.jpg HTTP/1.1" 404 2577
INFO 2019-01-16 09:27:37,606 basehttp 124 "GET /static/js/base/common.js HTTP/1.1" 200 223
INFO 2019-01-16 09:27:37,628 basehttp 124 "GET /static/js/index.js HTTP/1.1" 200 1510
WARNING 2019-01-16 09:27:37,646 log 228 Not Found: /images/python_advanced.jpg
WARNING 2019-01-16 09:27:37,656 basehttp 124 "GET /images/python_advanced.jpg HTTP/1.1" 404 2607
WARNING 2019-01-16 09:27:37,656 log 228 Not Found: /images/python_function.jpg
WARNING 2019-01-16 09:27:37,665 basehttp 124 "GET /images/python_function.jpg HTTP/1.1" 404 2607
WARNING 2019-01-16 09:27:37,653 log 228 Not Found: /images/jichujiaochen.jpeg
WARNING 2019-01-16 09:27:37,671 basehttp 124 "GET /images/jichujiaochen.jpeg HTTP/1.1" 404 2604
WARNING 2019-01-16 09:27:37,663 log 228 Not Found: /images/english.jpg
WARNING 2019-01-16 09:27:37,677 basehttp 124 "GET /images/english.jpg HTTP/1.1" 404 2583
WARNING 2019-01-16 09:27:37,690 log 228 Not Found: /images/python_web.jpg
WARNING 2019-01-16 09:27:37,692 basehttp 124 "GET /images/python_web.jpg HTTP/1.1" 404 2592
INFO 2019-01-16 09:32:03,405 basehttp 124 "GET / HTTP/1.1" 200 17211
INFO 2019-01-16 09:32:03,466 basehttp 124 "GET /static/images/jichujiaochen.jpeg HTTP/1.1" 200 11286
INFO 2019-01-16 09:32:03,489 basehttp 124 "GET /static/images/python_gui.jpg HTTP/1.1" 200 24129
INFO 2019-01-16 09:32:03,492 basehttp 124 "GET /static/images/python_function.jpg HTTP/1.1" 200 27960
INFO 2019-01-16 09:32:03,518 basehttp 124 "GET /static/images/linux.jpg HTTP/1.1" 200 62189
INFO 2019-01-16 09:32:03,519 basehttp 124 "GET /static/images/python_web.jpg HTTP/1.1" 200 45717
INFO 2019-01-16 09:32:03,536 basehttp 124 "GET /static/images/python_advanced.jpg HTTP/1.1" 200 120059
INFO 2019-01-16 09:32:03,549 basehttp 124 "GET /static/images/english.jpg HTTP/1.1" 200 137605
INFO 2019-01-16 14:36:22,796 basehttp 124 "GET / HTTP/1.1" 200 16476
WARNING 2019-01-16 14:38:48,914 log 228 Not Found: /course/course.html
WARNING 2019-01-16 14:38:48,915 basehttp 124 "GET /course/course.html HTTP/1.1" 404 2652
WARNING 2019-01-16 14:40:22,396 log 228 Not Found: /index.html
WARNING 2019-01-16 14:40:22,398 basehttp 124 "GET /index.html HTTP/1.1" 404 2559
INFO 2019-01-16 14:42:01,826 basehttp 124 "GET / HTTP/1.1" 200 16467
INFO 2019-01-16 14:42:03,146 basehttp 124 "GET / HTTP/1.1" 200 16467
INFO 2019-01-16 14:42:05,828 basehttp 124 "GET / HTTP/1.1" 200 16467
INFO 2019-01-16 14:42:08,942 basehttp 124 "GET / HTTP/1.1" 200 16467
ERROR 2019-01-16 14:42:38,950 log 228 Internal Server Error: /
Traceback (most recent call last):
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pyvip/MyProject/youkou_djT/apps/news/views.py", line 11, in index
    return render(request,'news/index.html')
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/defaulttags.py", line 442, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/urls/resolvers.py", line 622, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'course' not found. 'course' is not a valid view function or pattern name.
ERROR 2019-01-16 14:42:38,963 basehttp 124 "GET / HTTP/1.1" 500 134793
ERROR 2019-01-16 14:42:41,270 log 228 Internal Server Error: /
Traceback (most recent call last):
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pyvip/MyProject/youkou_djT/apps/news/views.py", line 11, in index
    return render(request,'news/index.html')
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/defaulttags.py", line 442, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/urls/resolvers.py", line 622, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'course' not found. 'course' is not a valid view function or pattern name.
ERROR 2019-01-16 14:42:41,283 basehttp 124 "GET / HTTP/1.1" 500 134645
ERROR 2019-01-16 14:42:47,026 log 228 Internal Server Error: /
Traceback (most recent call last):
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pyvip/MyProject/youkou_djT/apps/news/views.py", line 11, in index
    return render(request,'news/index.html')
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/defaulttags.py", line 442, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/urls/resolvers.py", line 622, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'course' not found. 'course' is not a valid view function or pattern name.
ERROR 2019-01-16 14:42:47,041 basehttp 124 "GET / HTTP/1.1" 500 134645
ERROR 2019-01-16 14:43:09,995 log 228 Internal Server Error: /
Traceback (most recent call last):
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pyvip/MyProject/youkou_djT/apps/news/views.py", line 11, in index
    return render(request,'news/index.html')
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/defaulttags.py", line 442, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/urls/resolvers.py", line 622, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'course' not found. 'course' is not a valid view function or pattern name.
ERROR 2019-01-16 14:43:10,018 basehttp 124 "GET / HTTP/1.1" 500 133766
WARNING 2019-01-16 14:43:21,160 log 228 Not Found: /blog/
WARNING 2019-01-16 14:43:21,163 basehttp 124 "GET /blog/ HTTP/1.1" 404 2544
ERROR 2019-01-16 14:43:26,115 log 228 Internal Server Error: /
Traceback (most recent call last):
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pyvip/MyProject/youkou_djT/apps/news/views.py", line 11, in index
    return render(request,'news/index.html')
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/defaulttags.py", line 442, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/urls/resolvers.py", line 622, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'course' not found. 'course' is not a valid view function or pattern name.
ERROR 2019-01-16 14:43:26,126 basehttp 124 "GET / HTTP/1.1" 500 133631
ERROR 2019-01-16 14:44:08,548 log 228 Internal Server Error: /
Traceback (most recent call last):
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pyvip/MyProject/youkou_djT/apps/news/views.py", line 11, in index
    return render(request,'news/index.html')
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/template/defaulttags.py", line 442, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/urls/resolvers.py", line 622, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'course' not found. 'course' is not a valid view function or pattern name.
ERROR 2019-01-16 14:44:08,564 basehttp 124 "GET / HTTP/1.1" 500 133766
INFO 2019-01-16 14:44:51,675 basehttp 124 "GET / HTTP/1.1" 200 16461
INFO 2019-01-16 14:44:53,382 basehttp 124 "GET /course/course/ HTTP/1.1" 200 3951
WARNING 2019-01-16 14:44:53,403 log 228 Not Found: /course/css/base/reset.css
WARNING 2019-01-16 14:44:53,413 basehttp 124 "GET /course/css/base/reset.css HTTP/1.1" 404 2673
WARNING 2019-01-16 14:44:53,418 log 228 Not Found: /course/css/course/course.css
WARNING 2019-01-16 14:44:53,411 log 228 Not Found: /course/css/base/common.css
WARNING 2019-01-16 14:44:53,424 basehttp 124 "GET /course/css/base/common.css HTTP/1.1" 404 2676
WARNING 2019-01-16 14:44:53,425 basehttp 124 "GET /course/css/course/course.css HTTP/1.1" 404 2682
WARNING 2019-01-16 14:44:53,430 log 228 Not Found: /course/images/python_advanced.jpg
WARNING 2019-01-16 14:44:53,423 log 228 Not Found: /course/course/js/common.js
WARNING 2019-01-16 14:44:53,437 basehttp 124 "GET /course/course/js/common.js HTTP/1.1" 404 2676
WARNING 2019-01-16 14:44:53,438 basehttp 124 "GET /course/images/python_advanced.jpg HTTP/1.1" 404 2697
WARNING 2019-01-16 14:44:53,436 log 228 Not Found: /course/images/python_web.jpg
WARNING 2019-01-16 14:44:53,439 basehttp 124 "GET /course/images/python_web.jpg HTTP/1.1" 404 2682
WARNING 2019-01-16 14:44:53,456 log 228 Not Found: /course/course/js/common.js
WARNING 2019-01-16 14:44:53,458 basehttp 124 "GET /course/course/js/common.js HTTP/1.1" 404 2676
INFO 2019-01-16 14:44:55,766 basehttp 124 "GET / HTTP/1.1" 200 16461
INFO 2019-01-16 14:44:56,477 basehttp 124 "GET /course/course/ HTTP/1.1" 200 3951
WARNING 2019-01-16 14:44:56,497 log 228 Not Found: /course/css/base/reset.css
WARNING 2019-01-16 14:44:56,503 basehttp 124 "GET /course/css/base/reset.css HTTP/1.1" 404 2673
WARNING 2019-01-16 14:44:56,502 log 228 Not Found: /course/css/base/common.css
WARNING 2019-01-16 14:44:56,508 basehttp 124 "GET /course/css/base/common.css HTTP/1.1" 404 2676
WARNING 2019-01-16 14:44:56,517 log 228 Not Found: /course/css/course/course.css
WARNING 2019-01-16 14:44:56,523 basehttp 124 "GET /course/css/course/course.css HTTP/1.1" 404 2682
WARNING 2019-01-16 14:44:56,522 log 228 Not Found: /course/images/python_advanced.jpg
WARNING 2019-01-16 14:44:56,534 basehttp 124 "GET /course/images/python_advanced.jpg HTTP/1.1" 404 2697
WARNING 2019-01-16 14:44:56,528 log 228 Not Found: /course/course/js/common.js
WARNING 2019-01-16 14:44:56,536 basehttp 124 "GET /course/course/js/common.js HTTP/1.1" 404 2676
WARNING 2019-01-16 14:44:56,533 log 228 Not Found: /course/images/python_web.jpg
WARNING 2019-01-16 14:44:56,537 basehttp 124 "GET /course/images/python_web.jpg HTTP/1.1" 404 2682
INFO 2019-01-16 14:45:39,180 basehttp 124 "GET / HTTP/1.1" 200 16443
INFO 2019-01-16 14:45:41,853 basehttp 124 "GET /doc/ HTTP/1.1" 200 7633
INFO 2019-01-16 14:45:41,874 basehttp 124 "GET /static/css/doc/docDownload.css HTTP/1.1" 200 2121
WARNING 2019-01-16 14:45:43,594 log 228 Not Found: /course/course.html
WARNING 2019-01-16 14:45:43,595 basehttp 124 "GET /course/course.html HTTP/1.1" 404 2652
WARNING 2019-01-16 14:45:47,406 log 228 Not Found: /course/course.html
WARNING 2019-01-16 14:45:47,408 basehttp 124 "GET /course/course.html HTTP/1.1" 404 2652
INFO 2019-01-16 14:45:56,999 basehttp 124 "GET / HTTP/1.1" 200 16443
INFO 2019-01-16 14:45:57,857 basehttp 124 "GET / HTTP/1.1" 200 16443
INFO 2019-01-16 14:45:58,373 basehttp 124 "GET /course/course/ HTTP/1.1" 200 3951
WARNING 2019-01-16 14:45:58,392 log 228 Not Found: /course/css/base/reset.css
WARNING 2019-01-16 14:45:58,398 basehttp 124 "GET /course/css/base/reset.css HTTP/1.1" 404 2673
WARNING 2019-01-16 14:45:58,397 log 228 Not Found: /course/css/base/common.css
WARNING 2019-01-16 14:45:58,408 basehttp 124 "GET /course/css/base/common.css HTTP/1.1" 404 2676
WARNING 2019-01-16 14:45:58,405 log 228 Not Found: /course/css/course/course.css
WARNING 2019-01-16 14:45:58,414 basehttp 124 "GET /course/css/course/course.css HTTP/1.1" 404 2682
WARNING 2019-01-16 14:45:58,413 log 228 Not Found: /course/course/js/common.js
WARNING 2019-01-16 14:45:58,421 basehttp 124 "GET /course/course/js/common.js HTTP/1.1" 404 2676
WARNING 2019-01-16 14:45:58,420 log 228 Not Found: /course/images/python_advanced.jpg
WARNING 2019-01-16 14:45:58,429 basehttp 124 "GET /course/images/python_advanced.jpg HTTP/1.1" 404 2697
WARNING 2019-01-16 14:45:58,436 log 228 Not Found: /course/images/python_web.jpg
WARNING 2019-01-16 14:45:58,437 basehttp 124 "GET /course/images/python_web.jpg HTTP/1.1" 404 2682
INFO 2019-01-16 14:52:42,582 basehttp 124 "GET / HTTP/1.1" 200 16443
INFO 2019-01-16 14:52:45,428 basehttp 124 "GET /course/course/ HTTP/1.1" 200 3951
WARNING 2019-01-16 14:52:45,447 log 228 Not Found: /course/css/base/reset.css
WARNING 2019-01-16 14:52:45,454 basehttp 124 "GET /course/css/base/reset.css HTTP/1.1" 404 2673
WARNING 2019-01-16 14:52:45,453 log 228 Not Found: /course/css/course/course.css
WARNING 2019-01-16 14:52:45,457 basehttp 124 "GET /course/css/course/course.css HTTP/1.1" 404 2682
WARNING 2019-01-16 14:52:45,463 log 228 Not Found: /course/css/base/common.css
WARNING 2019-01-16 14:52:45,473 basehttp 124 "GET /course/css/base/common.css HTTP/1.1" 404 2676
WARNING 2019-01-16 14:52:45,468 log 228 Not Found: /course/course/js/common.js
WARNING 2019-01-16 14:52:45,474 basehttp 124 "GET /course/course/js/common.js HTTP/1.1" 404 2676
WARNING 2019-01-16 14:52:45,472 log 228 Not Found: /course/images/python_web.jpg
WARNING 2019-01-16 14:52:45,476 basehttp 124 "GET /course/images/python_web.jpg HTTP/1.1" 404 2682
WARNING 2019-01-16 14:52:45,480 log 228 Not Found: /course/images/python_advanced.jpg
WARNING 2019-01-16 14:52:45,483 basehttp 124 "GET /course/images/python_advanced.jpg HTTP/1.1" 404 2697
WARNING 2019-01-16 14:52:45,497 log 228 Not Found: /course/course/js/common.js
WARNING 2019-01-16 14:52:45,498 basehttp 124 "GET /course/course/js/common.js HTTP/1.1" 404 2676
INFO 2019-01-16 14:52:49,077 basehttp 124 "GET /doc/ HTTP/1.1" 200 8836
INFO 2019-01-16 14:54:19,669 basehttp 124 "GET / HTTP/1.1" 200 16443
INFO 2019-01-16 14:54:22,111 basehttp 124 "GET /doc/ HTTP/1.1" 200 5130
INFO 2019-01-16 14:54:38,895 basehttp 124 "GET / HTTP/1.1" 200 16443
INFO 2019-01-16 14:54:45,367 basehttp 124 "GET / HTTP/1.1" 200 16443
INFO 2019-01-16 14:54:46,406 basehttp 124 "GET /doc/ HTTP/1.1" 200 2889
INFO 2019-01-16 14:54:55,260 basehttp 124 "GET / HTTP/1.1" 200 16443
INFO 2019-01-16 14:54:56,544 basehttp 124 "GET /doc/ HTTP/1.1" 200 8836
INFO 2019-01-16 15:00:09,355 basehttp 124 "GET / HTTP/1.1" 200 16443
INFO 2019-01-16 15:00:10,444 basehttp 124 "GET /doc/ HTTP/1.1" 200 5127
INFO 2019-01-16 15:02:26,568 basehttp 124 "GET / HTTP/1.1" 200 16443
INFO 2019-01-16 15:05:56,112 basehttp 124 "GET / HTTP/1.1" 200 16445
INFO 2019-01-16 15:05:57,410 basehttp 124 "GET /doc/ HTTP/1.1" 200 7510
INFO 2019-01-16 15:14:14,464 basehttp 124 "GET / HTTP/1.1" 200 16435
INFO 2019-01-16 15:14:16,012 basehttp 124 "GET /search/ HTTP/1.1" 200 12364
WARNING 2019-01-16 15:14:16,043 log 228 Not Found: /images/python_gui.jpg
WARNING 2019-01-16 15:14:16,050 basehttp 124 "GET /images/python_gui.jpg HTTP/1.1" 404 2761
WARNING 2019-01-16 15:14:16,054 log 228 Not Found: /search/js/common.js
WARNING 2019-01-16 15:14:16,066 basehttp 124 "GET /search/js/common.js HTTP/1.1" 404 2755
INFO 2019-01-16 15:14:16,059 basehttp 124 "GET /static/css/news/search.css HTTP/1.1" 200 2803
WARNING 2019-01-16 15:14:16,069 log 228 Not Found: /js/index.js
WARNING 2019-01-16 15:14:16,076 basehttp 124 "GET /js/index.js HTTP/1.1" 404 2731
WARNING 2019-01-16 15:14:16,065 log 228 Not Found: /images/python_advanced.jpg
WARNING 2019-01-16 15:14:16,078 basehttp 124 "GET /images/python_advanced.jpg HTTP/1.1" 404 2776
WARNING 2019-01-16 15:14:16,075 log 228 Not Found: /images/jichujiaochen.jpeg
WARNING 2019-01-16 15:14:16,087 basehttp 124 "GET /images/jichujiaochen.jpeg HTTP/1.1" 404 2773
WARNING 2019-01-16 15:14:16,086 log 228 Not Found: /images/python_web.jpg
WARNING 2019-01-16 15:14:16,089 basehttp 124 "GET /images/python_web.jpg HTTP/1.1" 404 2761
WARNING 2019-01-16 15:14:16,100 log 228 Not Found: /search/js/common.js
WARNING 2019-01-16 15:14:16,101 basehttp 124 "GET /search/js/common.js HTTP/1.1" 404 2755
WARNING 2019-01-16 15:14:16,116 log 228 Not Found: /js/index.js
WARNING 2019-01-16 15:14:16,117 basehttp 124 "GET /js/index.js HTTP/1.1" 404 2731
INFO 2019-01-16 15:15:31,660 basehttp 124 "GET / HTTP/1.1" 200 16435
INFO 2019-01-16 15:15:32,519 basehttp 124 "GET /search/ HTTP/1.1" 200 12406
WARNING 2019-01-16 15:15:32,533 log 228 Not Found: /images/python_gui.jpg
WARNING 2019-01-16 15:15:32,534 basehttp 124 "GET /images/python_gui.jpg HTTP/1.1" 404 2761
WARNING 2019-01-16 15:15:32,544 log 228 Not Found: /search/js/common.js
WARNING 2019-01-16 15:15:32,549 basehttp 124 "GET /search/js/common.js HTTP/1.1" 404 2755
WARNING 2019-01-16 15:15:32,556 log 228 Not Found: /js/index.js
WARNING 2019-01-16 15:15:32,557 basehttp 124 "GET /js/index.js HTTP/1.1" 404 2731
INFO 2019-01-16 15:16:01,096 basehttp 124 "GET /search/ HTTP/1.1" 200 12406
WARNING 2019-01-16 15:16:01,114 log 228 Not Found: /images/python_gui.jpg
WARNING 2019-01-16 15:16:01,115 basehttp 124 "GET /images/python_gui.jpg HTTP/1.1" 404 2761
WARNING 2019-01-16 15:16:01,123 log 228 Not Found: /search/js/common.js
WARNING 2019-01-16 15:16:01,129 basehttp 124 "GET /search/js/common.js HTTP/1.1" 404 2755
WARNING 2019-01-16 15:16:01,134 log 228 Not Found: /js/index.js
WARNING 2019-01-16 15:16:01,138 basehttp 124 "GET /js/index.js HTTP/1.1" 404 2731
INFO 2019-01-16 15:16:05,588 basehttp 124 "GET /search/ HTTP/1.1" 200 12416
WARNING 2019-01-16 15:16:05,612 log 228 Not Found: /search/js/common.js
WARNING 2019-01-16 15:16:05,619 basehttp 124 "GET /search/js/common.js HTTP/1.1" 404 2755
WARNING 2019-01-16 15:16:05,618 log 228 Not Found: /js/index.js
WARNING 2019-01-16 15:16:05,623 basehttp 124 "GET /js/index.js HTTP/1.1" 404 2731
INFO 2019-01-16 15:52:53,501 basehttp 124 "GET / HTTP/1.1" 200 16435
WARNING 2019-01-16 15:52:55,068 log 228 Not Found: /users/login.html
WARNING 2019-01-16 15:52:55,069 basehttp 124 "GET /users/login.html HTTP/1.1" 404 2992
INFO 2019-01-16 15:53:47,801 basehttp 124 "GET / HTTP/1.1" 200 16423
INFO 2019-01-16 15:53:49,206 basehttp 124 "GET /users/login/ HTTP/1.1" 200 7484
INFO 2019-01-16 15:53:52,614 basehttp 124 "GET /users/login/ HTTP/1.1" 200 7484
INFO 2019-01-16 15:54:23,468 basehttp 124 "GET / HTTP/1.1" 200 16423
INFO 2019-01-16 15:54:24,755 basehttp 124 "GET /users/login/ HTTP/1.1" 200 7483
INFO 2019-01-16 15:54:27,811 basehttp 124 "GET /users/register/ HTTP/1.1" 200 8153
WARNING 2019-01-16 15:54:27,832 log 228 Not Found: /users/images/captcha.png
WARNING 2019-01-16 15:54:27,834 basehttp 124 "GET /users/images/captcha.png HTTP/1.1" 404 3016
INFO 2019-01-16 15:56:52,200 basehttp 124 "GET / HTTP/1.1" 200 16423
INFO 2019-01-16 15:56:53,375 basehttp 124 "GET /users/login/ HTTP/1.1" 200 7547
INFO 2019-01-16 15:56:53,412 basehttp 124 "GET /static/css/authPro/auth.css HTTP/1.1" 200 3286
INFO 2019-01-16 15:56:56,101 basehttp 124 "GET /users/register/ HTTP/1.1" 200 8206
WARNING 2019-01-16 15:56:56,122 log 228 Not Found: /users/css/authPro/auth.css
WARNING 2019-01-16 15:56:56,128 basehttp 124 "GET /users/css/authPro/auth.css HTTP/1.1" 404 3022
WARNING 2019-01-16 15:56:56,127 log 228 Not Found: /users/images/captcha.png
WARNING 2019-01-16 15:56:56,130 basehttp 124 "GET /users/images/captcha.png HTTP/1.1" 404 3016
INFO 2019-01-16 15:56:57,774 basehttp 124 "GET /users/login/ HTTP/1.1" 200 7547
INFO 2019-01-16 15:57:22,512 basehttp 124 "GET /users/login/ HTTP/1.1" 200 7547
INFO 2019-01-16 15:57:24,516 basehttp 124 "GET /users/register/ HTTP/1.1" 200 8216
WARNING 2019-01-16 15:57:24,532 log 228 Not Found: /users/images/captcha.png
WARNING 2019-01-16 15:57:24,534 basehttp 124 "GET /users/images/captcha.png HTTP/1.1" 404 3016
INFO 2019-01-16 15:58:15,568 basehttp 124 "GET /users/login/ HTTP/1.1" 200 7484
INFO 2019-01-16 15:58:18,135 basehttp 124 "GET /users/login/ HTTP/1.1" 200 7484
INFO 2019-01-16 15:58:28,567 basehttp 124 "GET /users/login/ HTTP/1.1" 200 7484
INFO 2019-01-16 15:58:32,509 basehttp 124 "GET /users/login/ HTTP/1.1" 200 7547
INFO 2019-01-16 15:59:34,306 basehttp 124 "GET /users/login/ HTTP/1.1" 200 3837
INFO 2019-01-16 16:04:44,713 basehttp 124 "GET /users/login/ HTTP/1.1" 200 3837
INFO 2019-01-16 16:04:45,905 basehttp 124 "GET /users/login/ HTTP/1.1" 200 3837
INFO 2019-01-16 16:04:46,673 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4506
WARNING 2019-01-16 16:04:46,698 log 228 Not Found: /users/images/captcha.png
WARNING 2019-01-16 16:04:46,699 basehttp 124 "GET /users/images/captcha.png HTTP/1.1" 404 3016
INFO 2019-01-16 16:04:47,586 basehttp 124 "GET / HTTP/1.1" 200 16423
INFO 2019-01-16 16:04:50,280 basehttp 124 "GET /doc/ HTTP/1.1" 200 5099
INFO 2019-01-16 16:04:53,417 basehttp 124 "GET /course/ HTTP/1.1" 200 4192
WARNING 2019-01-16 16:04:53,442 log 228 Not Found: /images/python_web.jpg
WARNING 2019-01-16 16:04:53,446 basehttp 124 "GET /images/python_web.jpg HTTP/1.1" 404 2761
INFO 2019-01-16 16:04:53,446 basehttp 124 "GET /static/css/course/course.css HTTP/1.1" 200 1916
WARNING 2019-01-16 16:04:53,445 log 228 Not Found: /images/python_advanced.jpg
WARNING 2019-01-16 16:04:53,448 basehttp 124 "GET /images/python_advanced.jpg HTTP/1.1" 404 2776
INFO 2019-01-16 16:04:56,892 basehttp 124 "GET /course/ HTTP/1.1" 200 4192
WARNING 2019-01-16 16:04:56,918 log 228 Not Found: /images/python_advanced.jpg
WARNING 2019-01-16 16:04:56,921 basehttp 124 "GET /images/python_advanced.jpg HTTP/1.1" 404 2776
WARNING 2019-01-16 16:04:56,926 log 228 Not Found: /images/python_web.jpg
WARNING 2019-01-16 16:04:56,928 basehttp 124 "GET /images/python_web.jpg HTTP/1.1" 404 2761
INFO 2019-01-16 16:05:17,593 basehttp 124 "GET /course/ HTTP/1.1" 200 4192
WARNING 2019-01-16 16:05:17,619 log 228 Not Found: /images/python_advanced.jpg
WARNING 2019-01-16 16:05:17,620 basehttp 124 "GET /images/python_advanced.jpg HTTP/1.1" 404 2776
WARNING 2019-01-16 16:05:17,629 log 228 Not Found: /images/python_web.jpg
WARNING 2019-01-16 16:05:17,630 basehttp 124 "GET /images/python_web.jpg HTTP/1.1" 404 2761
INFO 2019-01-16 16:05:21,575 basehttp 124 "GET /course/ HTTP/1.1" 200 7902
WARNING 2019-01-16 16:05:21,605 log 228 Not Found: /images/python_advanced.jpg
WARNING 2019-01-16 16:05:21,617 basehttp 124 "GET /images/python_advanced.jpg HTTP/1.1" 404 2776
WARNING 2019-01-16 16:05:21,615 log 228 Not Found: /images/python_web.jpg
WARNING 2019-01-16 16:05:21,622 basehttp 124 "GET /images/python_web.jpg HTTP/1.1" 404 2761
INFO 2019-01-16 16:06:18,810 basehttp 124 "GET /course/ HTTP/1.1" 200 7922
INFO 2019-01-16 16:06:51,341 basehttp 124 "GET /course/ HTTP/1.1" 200 4212
INFO 2019-01-16 16:07:11,171 basehttp 124 "GET /course/ HTTP/1.1" 200 4212
INFO 2019-01-16 16:07:16,285 basehttp 124 "GET /doc/ HTTP/1.1" 200 5099
INFO 2019-01-16 16:07:40,050 basehttp 124 "GET /doc/ HTTP/1.1" 200 8809
INFO 2019-01-16 16:10:49,252 basehttp 124 "GET /course/ HTTP/1.1" 200 4212
INFO 2019-01-16 16:10:50,315 basehttp 124 "GET / HTTP/1.1" 200 16415
INFO 2019-01-16 16:10:51,030 basehttp 124 "GET /course/ HTTP/1.1" 200 4212
INFO 2019-01-16 16:10:51,616 basehttp 124 "GET /doc/ HTTP/1.1" 200 7626
ERROR 2019-01-16 16:18:15,502 log 228 Internal Server Error: /one/
Traceback (most recent call last):
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 190, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'youkou_djT.django_session' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 241, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 212, in inner
    if not self.has_permission(request):
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 186, in has_permission
    return request.user.is_active and request.user.is_staff
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/utils/functional.py", line 213, in inner
    self._setup()
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/utils/functional.py", line 347, in _setup
    self._wrapped = self._setupfunc()
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/contrib/auth/middleware.py", line 24, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/contrib/auth/middleware.py", line 12, in get_user
    request._cached_user = auth.get_user(request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 182, in get_user
    user_id = _get_user_session_key(request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 59, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 55, in __getitem__
    return self._session[key]
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 43, in load
    s = self._get_session_from_db()
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 34, in _get_session_from_db
    expire_date__gt=timezone.now()
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/models/query.py", line 393, in get
    num = len(clone)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/models/query.py", line 250, in __len__
    self._fetch_all()
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/models/query.py", line 1186, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1065, in execute_sql
    cursor.execute(sql, params)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.ProgrammingError: (1146, "Table 'youkou_djT.django_session' doesn't exist")
ERROR 2019-01-16 16:18:15,536 basehttp 124 "GET /one/ HTTP/1.1" 500 262326
INFO 2019-01-16 16:19:04,832 basehttp 124 "GET / HTTP/1.1" 200 16415
INFO 2019-01-16 16:19:08,645 basehttp 124 "GET / HTTP/1.1" 200 16415
ERROR 2019-01-16 16:19:19,736 log 228 Internal Server Error: /one/
Traceback (most recent call last):
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 190, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'youkou_djT.django_session' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 241, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 212, in inner
    if not self.has_permission(request):
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 186, in has_permission
    return request.user.is_active and request.user.is_staff
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/utils/functional.py", line 213, in inner
    self._setup()
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/utils/functional.py", line 347, in _setup
    self._wrapped = self._setupfunc()
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/contrib/auth/middleware.py", line 24, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/contrib/auth/middleware.py", line 12, in get_user
    request._cached_user = auth.get_user(request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 182, in get_user
    user_id = _get_user_session_key(request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 59, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 55, in __getitem__
    return self._session[key]
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 43, in load
    s = self._get_session_from_db()
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 34, in _get_session_from_db
    expire_date__gt=timezone.now()
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/models/query.py", line 393, in get
    num = len(clone)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/models/query.py", line 250, in __len__
    self._fetch_all()
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/models/query.py", line 1186, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1065, in execute_sql
    cursor.execute(sql, params)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.ProgrammingError: (1146, "Table 'youkou_djT.django_session' doesn't exist")
ERROR 2019-01-16 16:19:19,761 basehttp 124 "GET /one/ HTTP/1.1" 500 262330
INFO 2019-01-16 16:20:08,028 basehttp 124 "GET /one/ HTTP/1.1" 200 9
INFO 2019-01-16 16:21:25,524 basehttp 124 "GET / HTTP/1.1" 200 16415
INFO 2019-01-16 16:33:03,590 basehttp 124 "GET /doc/ HTTP/1.1" 200 7626
INFO 2019-01-16 16:33:04,214 basehttp 124 "GET /search/ HTTP/1.1" 200 12416
WARNING 2019-01-16 16:33:04,240 log 228 Not Found: /search/js/common.js
WARNING 2019-01-16 16:33:04,246 basehttp 124 "GET /search/js/common.js HTTP/1.1" 404 2651
WARNING 2019-01-16 16:33:04,245 log 228 Not Found: /js/index.js
WARNING 2019-01-16 16:33:04,249 basehttp 124 "GET /js/index.js HTTP/1.1" 404 2627
WARNING 2019-01-16 16:33:07,982 log 228 Not Found: /doc/docDownload.html
WARNING 2019-01-16 16:33:07,983 basehttp 124 "GET /doc/docDownload.html HTTP/1.1" 404 2715
WARNING 2019-01-16 16:33:18,400 log 228 Not Found: /course/course.html
WARNING 2019-01-16 16:33:18,401 basehttp 124 "GET /course/course.html HTTP/1.1" 404 2709
INFO 2019-01-16 16:33:23,897 basehttp 124 "GET /search/ HTTP/1.1" 200 12416
WARNING 2019-01-16 16:33:23,914 log 228 Not Found: /search/js/common.js
WARNING 2019-01-16 16:33:23,922 basehttp 124 "GET /search/js/common.js HTTP/1.1" 404 2651
WARNING 2019-01-16 16:33:23,929 log 228 Not Found: /js/index.js
WARNING 2019-01-16 16:33:23,934 basehttp 124 "GET /js/index.js HTTP/1.1" 404 2627
WARNING 2019-01-16 16:33:26,570 log 228 Not Found: /course/course.html
WARNING 2019-01-16 16:33:26,570 basehttp 124 "GET /course/course.html HTTP/1.1" 404 2709
INFO 2019-01-16 16:33:36,538 basehttp 124 "GET / HTTP/1.1" 200 16415
INFO 2019-01-16 16:33:39,195 basehttp 124 "GET /course/ HTTP/1.1" 200 4212
INFO 2019-01-16 16:33:39,832 basehttp 124 "GET / HTTP/1.1" 200 16415
INFO 2019-01-16 16:33:45,310 basehttp 124 "GET /course/ HTTP/1.1" 200 4212
INFO 2019-01-16 16:33:46,477 basehttp 124 "GET /doc/ HTTP/1.1" 200 7626
INFO 2019-01-16 16:33:47,920 basehttp 124 "GET /search/ HTTP/1.1" 200 12416
WARNING 2019-01-16 16:33:47,944 log 228 Not Found: /search/js/common.js
WARNING 2019-01-16 16:33:47,953 basehttp 124 "GET /search/js/common.js HTTP/1.1" 404 2651
WARNING 2019-01-16 16:33:47,967 log 228 Not Found: /js/index.js
WARNING 2019-01-16 16:33:47,975 basehttp 124 "GET /js/index.js HTTP/1.1" 404 2627
INFO 2019-01-16 16:34:50,258 basehttp 124 "GET /search/ HTTP/1.1" 200 12411
WARNING 2019-01-16 16:34:50,282 log 228 Not Found: /search/js/common.js
WARNING 2019-01-16 16:34:50,284 basehttp 124 "GET /search/js/common.js HTTP/1.1" 404 2651
WARNING 2019-01-16 16:34:50,508 log 228 Not Found: /js/index.js
WARNING 2019-01-16 16:34:50,511 basehttp 124 "GET /js/index.js HTTP/1.1" 404 2627
WARNING 2019-01-16 16:34:57,410 log 228 Not Found: /search/search.html
WARNING 2019-01-16 16:34:57,411 basehttp 124 "GET /search/search.html HTTP/1.1" 404 2648
INFO 2019-01-16 16:35:02,564 basehttp 124 "GET / HTTP/1.1" 200 16415
INFO 2019-01-16 16:35:03,984 basehttp 124 "GET /search/ HTTP/1.1" 200 12411
WARNING 2019-01-16 16:35:04,008 log 228 Not Found: /search/js/common.js
WARNING 2019-01-16 16:35:04,015 basehttp 124 "GET /search/js/common.js HTTP/1.1" 404 2651
WARNING 2019-01-16 16:35:04,014 log 228 Not Found: /js/index.js
WARNING 2019-01-16 16:35:04,022 basehttp 124 "GET /js/index.js HTTP/1.1" 404 2627
INFO 2019-01-16 16:39:53,671 basehttp 124 "GET / HTTP/1.1" 200 16415
INFO 2019-01-16 16:39:54,684 basehttp 124 "GET /search/ HTTP/1.1" 200 10991
INFO 2019-01-16 16:39:54,697 basehttp 124 "GET /static/js/common.js HTTP/1.1" 200 223
INFO 2019-01-16 16:39:56,594 basehttp 124 "GET /search/ HTTP/1.1" 200 10991
INFO 2019-01-16 16:39:58,122 basehttp 124 "GET /search/ HTTP/1.1" 200 10991
INFO 2019-01-16 16:39:59,113 basehttp 124 "GET /search/ HTTP/1.1" 200 10991
WARNING 2019-01-16 17:12:34,441 log 228 Not Found: /register_test/
WARNING 2019-01-16 17:12:34,443 basehttp 124 "GET /register_test/ HTTP/1.1" 404 2636
WARNING 2019-01-16 17:13:41,219 log 228 Not Found: /register
WARNING 2019-01-16 17:13:41,222 basehttp 124 "GET /register HTTP/1.1" 404 2618
WARNING 2019-01-16 17:13:46,701 log 228 Not Found: /register/
WARNING 2019-01-16 17:13:46,704 basehttp 124 "GET /register/ HTTP/1.1" 404 2621
INFO 2019-01-16 17:14:00,487 basehttp 124 "GET /users/register_test/ HTTP/1.1" 200 4506
WARNING 2019-01-16 17:14:00,511 log 228 Not Found: /users/images/captcha.png
WARNING 2019-01-16 17:14:00,513 basehttp 124 "GET /users/images/captcha.png HTTP/1.1" 404 3101
INFO 2019-01-16 17:14:08,867 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4506
WARNING 2019-01-16 17:14:08,889 log 228 Not Found: /users/images/captcha.png
WARNING 2019-01-16 17:14:08,890 basehttp 124 "GET /users/images/captcha.png HTTP/1.1" 404 3101
INFO 2019-01-16 17:14:48,758 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4516
INFO 2019-01-16 17:14:48,774 basehttp 124 "GET /static/images/captcha.png HTTP/1.1" 200 4296
INFO 2019-01-16 17:15:30,973 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4516
INFO 2019-01-16 17:15:32,968 basehttp 124 "GET /course/ HTTP/1.1" 200 4212
INFO 2019-01-16 17:15:33,824 basehttp 124 "GET / HTTP/1.1" 200 16415
INFO 2019-01-16 17:15:34,512 basehttp 124 "GET /doc/ HTTP/1.1" 200 7626
INFO 2019-01-16 17:15:35,044 basehttp 124 "GET /search/ HTTP/1.1" 200 10991
INFO 2019-01-16 17:15:35,894 basehttp 124 "GET /users/login/ HTTP/1.1" 200 3837
INFO 2019-01-16 17:15:36,495 basehttp 124 "GET /course/ HTTP/1.1" 200 4212
INFO 2019-01-16 17:15:37,090 basehttp 124 "GET / HTTP/1.1" 200 16415
INFO 2019-01-16 17:15:37,989 basehttp 124 "GET /users/login/ HTTP/1.1" 200 3837
WARNING 2019-01-16 17:15:39,398 log 228 Forbidden (CSRF token missing or incorrect.): /users/login/
WARNING 2019-01-16 17:15:39,400 basehttp 124 "POST /users/login/ HTTP/1.1" 403 2508
INFO 2019-01-16 17:17:01,057 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4516
WARNING 2019-01-16 17:17:02,178 log 228 Forbidden (CSRF token missing or incorrect.): /users/register/
WARNING 2019-01-16 17:17:02,180 basehttp 124 "POST /users/register/ HTTP/1.1" 403 2508
INFO 2019-01-16 17:19:31,886 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4516
INFO 2019-01-16 17:19:35,826 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4516
INFO 2019-01-16 17:19:39,569 basehttp 124 "GET /users/login/ HTTP/1.1" 200 3837
INFO 2019-01-16 17:19:44,139 basehttp 124 "GET /users/login/ HTTP/1.1" 200 3837
INFO 2019-01-16 17:19:45,098 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4516
INFO 2019-01-16 17:19:45,762 basehttp 124 "GET /users/login/ HTTP/1.1" 200 3837
WARNING 2019-01-16 19:14:01,712 log 228 Not Found: /admin/
WARNING 2019-01-16 19:14:01,714 basehttp 124 "GET /admin/ HTTP/1.1" 404 2612
WARNING 2019-01-16 19:14:20,521 log 228 Not Found: /admin/
WARNING 2019-01-16 19:14:20,529 basehttp 124 "GET /admin/ HTTP/1.1" 404 2612
INFO 2019-01-16 19:14:22,909 basehttp 124 "GET /admin/ HTTP/1.1" 302 0
INFO 2019-01-16 19:14:23,017 basehttp 124 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1821
INFO 2019-01-16 19:14:23,092 basehttp 124 "GET /static/admin/css/login.css HTTP/1.1" 200 1203
INFO 2019-01-16 19:14:23,093 basehttp 124 "GET /static/admin/css/base.css HTTP/1.1" 200 16225
INFO 2019-01-16 19:14:23,100 basehttp 124 "GET /static/admin/css/responsive.css HTTP/1.1" 200 17976
INFO 2019-01-16 19:14:23,106 basehttp 124 "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
INFO 2019-01-16 19:14:23,127 basehttp 124 "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 80304
INFO 2019-01-16 19:14:23,160 basehttp 124 "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 81348
INFO 2019-01-16 19:14:33,537 basehttp 124 "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2019-01-16 19:14:33,587 basehttp 124 "GET /admin/ HTTP/1.1" 200 2580
INFO 2019-01-16 19:14:33,610 basehttp 124 "GET /static/admin/css/dashboard.css HTTP/1.1" 200 412
INFO 2019-01-16 19:14:33,627 basehttp 124 "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO 2019-01-16 19:14:33,636 basehttp 124 "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
INFO 2019-01-16 19:14:33,657 basehttp 124 "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 82564
INFO 2019-01-16 19:14:37,909 basehttp 124 "GET /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2019-01-16 19:14:37,940 basehttp 124 "GET /admin/ HTTP/1.1" 200 2580
INFO 2019-01-16 19:15:25,048 basehttp 124 "GET /admin/ HTTP/1.1" 200 2580
INFO 2019-01-16 19:15:31,004 basehttp 124 "GET / HTTP/1.1" 200 16415
INFO 2019-01-16 19:42:13,947 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4516
INFO 2019-01-18 22:33:18,900 basehttp 124 "GET /static/css/base/side.css HTTP/1.1" 200 4428
INFO 2019-01-18 22:33:18,907 basehttp 124 "GET /static/css/news/index.css HTTP/1.1" 200 5500
INFO 2019-01-18 22:33:18,929 basehttp 124 "GET /static/js/index.js HTTP/1.1" 200 1510
INFO 2019-01-18 22:33:18,932 basehttp 124 "GET /static/images/python_gui.jpg HTTP/1.1" 200 24129
INFO 2019-01-18 22:33:18,937 basehttp 124 "GET /static/js/base/common.js HTTP/1.1" 200 223
INFO 2019-01-18 22:33:18,946 basehttp 124 "GET /static/images/linux.jpg HTTP/1.1" 200 62189
INFO 2019-01-18 22:33:18,950 basehttp 124 "GET /static/images/python_function.jpg HTTP/1.1" 200 27960
INFO 2019-01-18 22:33:18,966 basehttp 124 "GET /static/images/python_advanced.jpg HTTP/1.1" 200 120059
INFO 2019-01-18 22:33:18,971 basehttp 124 "GET /static/images/jichujiaochen.jpeg HTTP/1.1" 200 11286
INFO 2019-01-18 22:33:18,975 basehttp 124 "GET /static/images/python_web.jpg HTTP/1.1" 200 45717
INFO 2019-01-18 22:33:18,996 basehttp 124 "GET /static/images/english.jpg HTTP/1.1" 200 137605
INFO 2019-01-18 22:33:19,063 basehttp 124 "GET /static/images/wechat.jpg HTTP/1.1" 200 24527
WARNING 2019-01-18 22:33:20,503 log 228 Not Found: /favicon.ico
WARNING 2019-01-18 22:33:20,504 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 3530
INFO 2019-01-18 22:33:20,601 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4724
INFO 2019-01-18 22:33:20,616 basehttp 124 "GET /static/css/authPro/auth.css HTTP/1.1" 200 3286
INFO 2019-01-18 22:33:20,622 basehttp 124 "GET /static/js/users/auth_bk.js HTTP/1.1" 200 2665
INFO 2019-01-18 22:33:20,690 views 61 Image code: FIZK
INFO 2019-01-18 22:33:20,691 basehttp 124 "GET /image_codes/e6fc2499-60bb-4bea-ab97-0d3af82b0ec8/ HTTP/1.1" 200 3156
INFO 2019-01-18 22:33:25,344 basehttp 124 "GET /usernames/python/ HTTP/1.1" 200 72
INFO 2019-01-18 22:39:28,843 basehttp 124 "GET / HTTP/1.1" 200 16466
INFO 2019-01-18 22:39:29,547 basehttp 124 "GET /static/js/base/message.js HTTP/1.1" 200 3572
INFO 2019-01-18 22:39:31,618 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4728
INFO 2019-01-18 22:39:31,639 basehttp 124 "GET /static/js/users/auth.js HTTP/1.1" 200 10769
INFO 2019-01-18 22:39:31,641 basehttp 124 "GET /static/js/base/message.js HTTP/1.1" 304 0
INFO 2019-01-18 22:39:31,707 views 61 Image code: YPIA
INFO 2019-01-18 22:39:31,708 basehttp 124 "GET /image_codes/ee0925d1-45e8-4a7c-ac04-4b92e68f0757/ HTTP/1.1" 200 3071
INFO 2019-01-18 22:39:35,753 basehttp 124 "GET /usernames/python/ HTTP/1.1" 200 72
INFO 2019-01-18 22:39:52,380 basehttp 124 "GET /mobiles/18811112222/ HTTP/1.1" 200 75
INFO 2019-01-18 22:40:25,501 basehttp 124 "GET /usernames/pyvip/ HTTP/1.1" 200 71
INFO 2019-01-18 22:40:33,475 basehttp 124 "GET /mobiles/15875723195/ HTTP/1.1" 200 75
INFO 2019-01-18 22:40:39,467 basehttp 124 "GET /mobiles/15875723195/ HTTP/1.1" 200 75
ERROR 2019-01-18 22:40:39,511 log 228 Internal Server Error: /sms_codes/
Traceback (most recent call last):
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/pyvip/MyProject/youkou_djT/apps/verifications/views.py", line 241, in post
    dict_data = json.load(json_data)
  File "/usr/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
AttributeError: 'bytes' object has no attribute 'read'
ERROR 2019-01-18 22:40:39,518 basehttp 124 "POST /sms_codes/ HTTP/1.1" 500 15132
INFO 2019-01-18 22:40:41,334 basehttp 124 "GET /mobiles/15875723195/ HTTP/1.1" 200 75
ERROR 2019-01-18 22:40:41,358 log 228 Internal Server Error: /sms_codes/
Traceback (most recent call last):
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/pyvip/MyProject/youkou_djT/apps/verifications/views.py", line 241, in post
    dict_data = json.load(json_data)
  File "/usr/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
AttributeError: 'bytes' object has no attribute 'read'
ERROR 2019-01-18 22:40:41,362 basehttp 124 "POST /sms_codes/ HTTP/1.1" 500 15132
INFO 2019-01-18 22:40:47,946 basehttp 124 "GET /mobiles/15875723195/ HTTP/1.1" 200 75
ERROR 2019-01-18 22:40:47,995 log 228 Internal Server Error: /sms_codes/
Traceback (most recent call last):
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/pyvip/MyProject/youkou_djT/apps/verifications/views.py", line 241, in post
    dict_data = json.load(json_data)
  File "/usr/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
AttributeError: 'bytes' object has no attribute 'read'
ERROR 2019-01-18 22:40:48,000 basehttp 124 "POST /sms_codes/ HTTP/1.1" 500 15132
INFO 2019-01-18 22:41:51,696 basehttp 124 "GET /mobiles/15875723195/ HTTP/1.1" 200 75
ERROR 2019-01-18 22:41:51,719 log 228 Internal Server Error: /sms_codes/
Traceback (most recent call last):
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/pyvip/MyProject/youkou_djT/apps/verifications/views.py", line 241, in post
    dict_data = json.load(json_data)
  File "/usr/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
AttributeError: 'bytes' object has no attribute 'read'
ERROR 2019-01-18 22:41:51,724 basehttp 124 "POST /sms_codes/ HTTP/1.1" 500 15132
INFO 2019-01-18 22:41:55,320 basehttp 124 "GET /mobiles/15875723195/ HTTP/1.1" 200 75
ERROR 2019-01-18 22:41:55,342 log 228 Internal Server Error: /sms_codes/
Traceback (most recent call last):
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/pyvip/MyProject/youkou_djT/apps/verifications/views.py", line 241, in post
    dict_data = json.load(json_data)
  File "/usr/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
AttributeError: 'bytes' object has no attribute 'read'
ERROR 2019-01-18 22:41:55,348 basehttp 124 "POST /sms_codes/ HTTP/1.1" 500 15132
INFO 2019-01-18 22:42:05,004 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4727
INFO 2019-01-18 22:42:05,019 basehttp 124 "GET /static/js/base/message.js HTTP/1.1" 304 0
INFO 2019-01-18 22:42:05,022 basehttp 124 "GET /static/js/users/auth.js HTTP/1.1" 304 0
INFO 2019-01-18 22:42:05,067 views 61 Image code: UAJN
INFO 2019-01-18 22:42:05,069 basehttp 124 "GET /image_codes/7e3f98d2-9ad7-48e7-8848-845330df0ec9/ HTTP/1.1" 200 3298
INFO 2019-01-18 22:42:09,431 basehttp 124 "GET /usernames/pyvip/ HTTP/1.1" 200 71
INFO 2019-01-18 22:42:17,162 basehttp 124 "GET /mobiles/15875723195/ HTTP/1.1" 200 75
INFO 2019-01-18 22:42:18,201 views 61 Image code: FBVC
INFO 2019-01-18 22:42:18,203 basehttp 124 "GET /image_codes/ee97d8fd-9a6c-4ce6-8072-8febb2c6ba97/ HTTP/1.1" 200 3354
INFO 2019-01-18 22:42:22,641 views 61 Image code: SXWA
INFO 2019-01-18 22:42:22,642 basehttp 124 "GET /image_codes/9d94a4b4-28b3-4d09-9c08-c45ef285fd5c/ HTTP/1.1" 200 3434
INFO 2019-01-18 22:42:27,774 basehttp 124 "GET /mobiles/15875723195/ HTTP/1.1" 200 75
ERROR 2019-01-18 22:42:27,825 log 228 Internal Server Error: /sms_codes/
Traceback (most recent call last):
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/pyvip/MyProject/youkou_djT/apps/verifications/views.py", line 241, in post
    dict_data = json.load(json_data)
  File "/usr/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
AttributeError: 'bytes' object has no attribute 'read'
ERROR 2019-01-18 22:42:27,829 basehttp 124 "POST /sms_codes/ HTTP/1.1" 500 15132
INFO 2019-01-18 22:43:29,510 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4727
INFO 2019-01-18 22:43:29,536 basehttp 124 "GET /static/js/base/message.js HTTP/1.1" 304 0
INFO 2019-01-18 22:43:29,614 views 61 Image code: IIB3
INFO 2019-01-18 22:43:29,616 basehttp 124 "GET /image_codes/701c6b9e-bdc8-4fda-bb5c-1fc27997bf6e/ HTTP/1.1" 200 3363
INFO 2019-01-18 22:43:36,234 basehttp 124 "GET /usernames/pyvip/ HTTP/1.1" 200 71
INFO 2019-01-18 22:43:43,505 basehttp 124 "GET /mobiles/15875723195/ HTTP/1.1" 200 75
INFO 2019-01-18 22:43:49,354 basehttp 124 "GET /mobiles/15875723195/ HTTP/1.1" 200 75
ERROR 2019-01-18 22:44:17,990 log 228 Internal Server Error: /sms_codes/
Traceback (most recent call last):
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/pyvip/MyProject/youkou_djT/apps/verifications/views.py", line 241, in post
    dict_data = json.load(json_data)
  File "/usr/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
AttributeError: 'bytes' object has no attribute 'read'
ERROR 2019-01-18 22:45:11,765 basehttp 124 "POST /sms_codes/ HTTP/1.1" 500 16339
INFO 2019-01-18 22:46:03,211 basehttp 124 "GET /usernames/pyvip/ HTTP/1.1" 200 71
INFO 2019-01-18 22:46:06,857 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4727
INFO 2019-01-18 22:46:06,895 basehttp 124 "GET /static/js/users/auth.js HTTP/1.1" 304 0
INFO 2019-01-18 22:46:06,897 basehttp 124 "GET /static/js/base/message.js HTTP/1.1" 304 0
INFO 2019-01-18 22:46:06,973 views 61 Image code: NUZL
INFO 2019-01-18 22:46:06,975 basehttp 124 "GET /image_codes/cc79a383-63b2-4f05-b541-36286ee382cd/ HTTP/1.1" 200 2944
INFO 2019-01-18 22:46:15,735 basehttp 124 "GET /usernames/pyvip/ HTTP/1.1" 200 71
INFO 2019-01-18 22:46:21,031 basehttp 124 "GET /mobiles/15875723195/ HTTP/1.1" 200 75
INFO 2019-01-18 22:46:26,024 basehttp 124 "GET /mobiles/15875723195/ HTTP/1.1" 200 75
ERROR 2019-01-18 22:47:33,125 log 228 Internal Server Error: /sms_codes/
Traceback (most recent call last):
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/pyvip/MyProject/youkou_djT/apps/verifications/views.py", line 241, in post
    dict_data = json.load(json_data)
  File "/usr/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
AttributeError: 'bytes' object has no attribute 'read'
INFO 2019-01-18 22:48:01,999 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4727
INFO 2019-01-18 22:48:02,017 basehttp 124 "GET /static/js/base/message.js HTTP/1.1" 304 0
INFO 2019-01-18 22:48:02,077 views 61 Image code: 8AEL
INFO 2019-01-18 22:48:02,078 basehttp 124 "GET /image_codes/dd0dc8b8-e25b-46b5-ab0d-dab31b36e839/ HTTP/1.1" 200 3183
INFO 2019-01-18 22:48:08,205 basehttp 124 "GET /usernames/pyvip/ HTTP/1.1" 200 71
INFO 2019-01-18 22:48:14,479 basehttp 124 "GET /mobiles/15875723195/ HTTP/1.1" 200 75
INFO 2019-01-18 22:48:14,534 views 61 Image code: SAGF
INFO 2019-01-18 22:48:14,535 basehttp 124 "GET /image_codes/2abd2d8a-7713-41dd-884b-39ab694b1b34/ HTTP/1.1" 200 3453
INFO 2019-01-18 22:48:21,859 basehttp 124 "GET /mobiles/15875723195/ HTTP/1.1" 200 75
ERROR 2019-01-18 22:48:21,905 log 228 Internal Server Error: /sms_codes/
Traceback (most recent call last):
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/pyvip/.virtualenvs/djT/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/pyvip/MyProject/youkou_djT/apps/verifications/views.py", line 241, in post
    dict_data = json.load(json_data)
  File "/usr/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
AttributeError: 'bytes' object has no attribute 'read'
ERROR 2019-01-18 22:48:21,911 basehttp 124 "POST /sms_codes/ HTTP/1.1" 500 15132
INFO 2019-01-18 22:49:26,353 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4727
INFO 2019-01-18 22:49:26,368 basehttp 124 "GET /static/js/base/message.js HTTP/1.1" 304 0
INFO 2019-01-18 22:49:26,372 basehttp 124 "GET /static/js/users/auth.js HTTP/1.1" 304 0
INFO 2019-01-18 22:49:26,423 views 61 Image code: AJUA
INFO 2019-01-18 22:49:26,425 basehttp 124 "GET /image_codes/ba55004e-6a70-4a23-803a-ea5a04623884/ HTTP/1.1" 200 3340
INFO 2019-01-18 22:49:31,428 basehttp 124 "GET /usernames/pyvip/ HTTP/1.1" 200 71
INFO 2019-01-18 22:49:37,291 basehttp 124 "GET /mobiles/15875723195/ HTTP/1.1" 200 75
INFO 2019-01-18 22:49:41,598 basehttp 124 "GET /mobiles/15875723195/ HTTP/1.1" 200 75
INFO 2019-01-18 22:49:41,614 views 270 Sms Code: 509165
WARNING 2019-01-18 22:49:42,164 views 287 发送验证码短信[失败][ mobile: 15875723195 ]
INFO 2019-01-18 22:49:42,168 basehttp 124 "POST /sms_codes/ HTTP/1.1" 200 99
INFO 2019-01-18 22:49:48,774 views 61 Image code: Y5IF
INFO 2019-01-18 22:49:48,775 basehttp 124 "GET /image_codes/e4763698-fa17-4883-b540-861c7fe378a0/ HTTP/1.1" 200 3087
INFO 2019-01-18 22:49:55,208 basehttp 124 "GET /mobiles/15875723195/ HTTP/1.1" 200 75
INFO 2019-01-18 22:49:55,222 basehttp 124 "POST /sms_codes/ HTTP/1.1" 200 123
INFO 2019-01-18 22:51:00,974 views 61 Image code: FMR6
INFO 2019-01-18 22:51:00,975 basehttp 124 "GET /image_codes/38992306-2ffb-4f55-bf8b-410e7574e177/ HTTP/1.1" 200 3367
INFO 2019-01-18 22:51:07,777 basehttp 124 "GET /mobiles/15875723195/ HTTP/1.1" 200 75
INFO 2019-01-18 22:51:07,796 views 270 Sms Code: 173175
WARNING 2019-01-18 22:51:08,366 views 287 发送验证码短信[失败][ mobile: 15875723195 ]
INFO 2019-01-18 22:51:08,368 basehttp 124 "POST /sms_codes/ HTTP/1.1" 200 99
INFO 2019-01-18 22:52:45,701 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4727
INFO 2019-01-18 22:52:45,720 basehttp 124 "GET /static/js/base/message.js HTTP/1.1" 304 0
INFO 2019-01-18 22:52:45,724 basehttp 124 "GET /static/js/users/auth.js HTTP/1.1" 304 0
INFO 2019-01-18 22:52:45,774 views 61 Image code: REPM
INFO 2019-01-18 22:52:45,775 basehttp 124 "GET /image_codes/988c43cd-8eba-4f8e-bfa9-2e48f83e0725/ HTTP/1.1" 200 3492
INFO 2019-01-18 22:52:53,095 basehttp 124 "GET /usernames/pyvip/ HTTP/1.1" 200 71
INFO 2019-01-18 22:52:58,971 basehttp 124 "GET /mobiles/15875723195/ HTTP/1.1" 200 75
INFO 2019-01-18 22:53:02,814 basehttp 124 "GET /mobiles/15875723195/ HTTP/1.1" 200 75
INFO 2019-01-18 22:53:02,857 views 270 Sms Code: 601671
WARNING 2019-01-18 22:53:03,406 views 287 发送验证码短信[失败][ mobile: 15875723195 ]
INFO 2019-01-18 22:53:03,408 basehttp 124 "POST /sms_codes/ HTTP/1.1" 200 99
INFO 2019-01-18 22:53:24,369 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4727
INFO 2019-01-18 22:53:24,464 views 61 Image code: PTMW
INFO 2019-01-18 22:53:24,465 basehttp 124 "GET /image_codes/71a5c4d3-e445-4869-9381-adf4c54e84bc/ HTTP/1.1" 200 3456
INFO 2019-01-18 22:53:31,753 basehttp 124 "GET /usernames/pyvip/ HTTP/1.1" 200 71
INFO 2019-01-18 22:53:36,412 basehttp 124 "GET /mobiles/15875723195/ HTTP/1.1" 200 75
INFO 2019-01-18 22:53:41,708 basehttp 124 "GET /mobiles/15875723195/ HTTP/1.1" 200 75
INFO 2019-01-18 22:54:05,749 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4727
INFO 2019-01-18 22:54:05,821 views 61 Image code: DV8J
INFO 2019-01-18 22:54:05,822 basehttp 124 "GET /image_codes/9073d316-22de-4793-a065-342cd67b1878/ HTTP/1.1" 200 2812
INFO 2019-01-18 22:56:35,516 basehttp 124 "GET /users/register/ HTTP/1.1" 200 4727
INFO 2019-01-18 22:56:35,545 basehttp 124 "GET /static/js/base/message.js HTTP/1.1" 304 0
INFO 2019-01-18 22:56:35,549 basehttp 124 "GET /static/js/users/auth.js HTTP/1.1" 304 0
INFO 2019-01-18 22:56:35,587 views 61 Image code: WTLV
INFO 2019-01-18 22:56:35,589 basehttp 124 "GET /image_codes/ca186af9-9e36-49b2-a28b-e68f2ef127aa/ HTTP/1.1" 200 3297
INFO 2019-01-18 22:56:40,453 basehttp 124 "GET /usernames/pyvip/ HTTP/1.1" 200 71
INFO 2019-01-18 22:56:46,119 basehttp 124 "GET /mobiles/17767100789/ HTTP/1.1" 200 75
INFO 2019-01-18 22:56:51,835 basehttp 124 "GET /mobiles/17767100789/ HTTP/1.1" 200 75
INFO 2019-01-18 22:56:51,854 views 270 Sms Code: 410743
INFO 2019-01-18 22:56:52,441 views 284 发送验证码短信[正常][ mobile: 17767100789 sms_code: 410743]
INFO 2019-01-18 22:56:52,443 basehttp 124 "POST /sms_codes/ HTTP/1.1" 200 96
